services:
  frontend:
    build: .
    ports:
      - 4200:4200
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - json-server

  json-server:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 3333:3333
    command: ["yarn", "db:server"]
